const MAX_NOTE_TITLE_LENGTH = 50;
const MAX_NOTE_CONTENT_LENGTH = 500;
const MAX_NOTES_IN_MEMORY = 25;

module.exports = {
  MAX_NOTE_TITLE_LENGTH,
  MAX_NOTE_CONTENT_LENGTH,
  MAX_NOTES_IN_MEMORY,
};
